name: Add A TestFilght Link

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: '应用名称【中间不要有英文双引号或英文竖线分隔符"|"】'
        required: false
        default: 'None'
      testflight_link:
        description: 'Testflight 公共测试的完整链接(非 TestFilght 链接请添加到 scripts/data/signup.md)'
        required: true
      table:
        description: '链接分类(可选值：`macos`, `ios`, `ios_game`, `chinese`)'
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64

      - name: Init Python Env
        run: pip install -r scripts/requirements.txt

      - name: Add A TestFilght Link
        run: python scripts/add_link.py "${{ github.event.inputs.testflight_link }}" "${{ github.event.inputs.table }}" "${{ github.event.inputs.app_name }}"

      - name: Git commit && push
        run: |
          git_diff=`git diff`
          git diff README.md >git_diff.md
          if [ -z "$git_diff" ]; then echo "Nothing Changed";exit; fi
          git config --global user.email "github_bot@noreply.github.com"
          git config --global user.name "github_bot"
          git add .
          git commit -m "Add A New Link"
          git push

      - name: Send Email
        uses: dawidd6/action-send-mail@master
        with:
            server_address: smtp.163.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: TestFlight Status Update
            to: vemodalen01@outlook.com
            from: GitHub Actions
            secure: true
            body: file://git_diff.md
            convert_markdown: true
            
            

