name: Order TestFilght Link Status

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: '指定 Python 版本 3.6+ （不建议修改）'
        required: false
        default: '3.8'
env: 
  TZ: Asia/Shanghai 
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      python_version: ${{ github.event.inputs.python_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Check env
        run: if [ -z "$python_version" ]; then python_version='3.8'; fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
          architecture: x64

      - name: Checkout main -> status_ordered
        run: |
          git config --global user.email "github_bot@noreply.github.com"
          git config --global user.name "github_bot"
          git pull --unshallow
          git checkout status_ordered
          git checkout origin/main db/sqlite3.db

      - name: Order TestFilght Link Status
        run: python scripts/order_status.py

      - name: Git commit && push
        run: |
          git_diff=`git diff`
          if [ -z "$git_diff" ]; then echo "Nothing Changed";exit; fi
          git add .
          git commit -m "Github Action Auto Updated - `date`"
          git push origin status_ordered
