name: Test

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: '应用名称【中间不要有英文双引号或英文竖线分隔符"|"】'
        required: false
        default: 'Shu'
      testflight_link:
        description: 'Testflight 公共测试的完整链接(非 TestFilght 链接请添加到 scripts/data/signup.md)'
        required: false
        default: 'https://testflight.apple.com/join/4nss4sdk'
      table:
        description: '链接分类(可选值：`macos`, `ios`, `ios_game`, `chinese`)'
        required: false
        default: 'ios'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64

      - name: Init Python Env
        run: pip install -r scripts/requirements.txt

      - name: Add A TestFilght Link
        run: python scripts/add_link.py "${{ github.event.inputs.testflight_link }}" "${{ github.event.inputs.table }}" "${{ github.event.inputs.app_name }}"

      - name: Git commit && push
        run: |
          git_diff=`git diff`
          if [ -z "$git_diff" ]; then echo "Nothing Changed";exit; fi
          echo "Status=OK" >>  $GITHUB_ENV
          git diff README.md | grep -P '^\+(?:(?!\+\+))' | sed -e 's/([^()]*)//g' |  sed 's/.//' > Recent_Update.md
          echo "TEST=$(`git diff README.md | grep -P '^\+(?:(?!\+\+))' | sed -e 's/([^()]*)//g' |  sed 's/.//'`)" >>  $GITHUB_ENV 
          name=`awk -F "|" '{print $2}' Recent_Update.md | tr -s "\n" " " | sed 's/^[ \t]*//g' | sed 's/[ \t]*$//g'`
          echo "NAME=$(awk -F "|" '{print $2}' Recent_Update.md | tr -s "\n" " " | sed 's/^[ \t]*//g' | sed 's/[ \t]*$//g')" >>  $GITHUB_ENV 

      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{env.TEST}}
          format: markdown