name: Update TestFilght Link Status

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      python_version:
        description: '指定 Python 版本 3.6+ （不建议修改）'
        required: false
        default: '3.8'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      python_version: ${{ github.event.inputs.python_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Check env
        run: if [ -z "$python_version" ]; then python_version='3.8'; fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
          architecture: x64
      - name: Init Python Env
        run: pip install -r scripts/requirements.txt
      - name: Update TestFilght Link Status
        run: python scripts/update_status.py

      - name: Git commit && push
        run: |
          git_diff=`git diff`
          git diff README.md | grep -P '^\+(?:(?!\+\+))' | sed -e 's/([^()]*)//g' |  sed 's/.//' > git_diff_1.md
          echo "NAME=$(awk '{print $2}' git_diff_1.md | tr -s "\n" "/")" >>  $GITHUB_ENV
          if [ -z "$git_diff" ]; then echo "Nothing Changed";exit; fi
          git config --global user.email "github_bot@noreply.github.com"
          git config --global user.name "github_bot"
          git add .
          git commit -m "Github Action Auto Updated - `date`"
          git push


      - name: Send Email
        if: git_diff != ""
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject:  (${{env.NAME}}) TestFlight Update  
          to: vemodalen01@outlook.com
          from: GitHub Actions
          secure: true
          body: file://git_diff_1.md
          convert_markdown: true                

          
